socket-name: /run/topolvm/lvmd.sock
device-classes:
  - name: ssd
    volume-group: myvg1
    default: true
    spare-gb: 10
    type: thin
    thin-pool:
        name: thinpool
        overprovision-ratio: 50.0
